server:
  port: 30081

spring:
  datasource:
    url: jdbc:mysql://124.70.40.151:3306/time_manager_system?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: w849027724
    driver-class-name: com.mysql.jdbc.Driver

global:
  config:
    author: wlj
    model: time-manager-service/time-manager-system

package:
  config:
    biz-module: system
    parent-path: com.time.manager.system
strategy:
  config:
    super-entity-class: com.time.manage.common.mybatis.entity.BaseEntity
    table-name: sys_resource,sys_role,sys_role_resource,sys_user,sys_user_role

