server:
  port: 30081

spring:
  datasource:
    url: jdbc:mysql://124.70.40.151:3306/time-wallet?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: w849027724
    driver-class-name: com.mysql.jdbc.Driver

global:
  config:
    author: wlj
    model: time-manager-service/time-manager-wallet

package:
  config:
    biz-module: wallet
    parent-path: com.time.manager.wallet
strategy:
  config:
    super-entity-class: com.time.manage.common.mybatis.entity.BaseEntity
    table-name: wallet

