server:
  port: 33001


spring:
  datasource:
    url: jdbc:mysql://124.70.40.151:3306/time_manager_test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: w849027724
    driver-class-name: com.mysql.cj.jdbc.Driver

redisson:
  address: redis://124.70.40.151:6379
  password: 123456
  database: 10

  #logger配置
logging:
  level:
    #日志级别
    root: DEBUG