server:
  port: 33001
spring:
  application:
    name: time-manager-cms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:30000
      config:
        server-addr: 127.0.0.1:30000
        file-extension: yml
        shared-dataids: application.yml

