server:
  port: 33001


spring:
  datasource:
    url: jdbc:mysql://149.28.213.252:3306/time_manager£¿characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


